In [9]:
#importing modules
import numpy as np 
import pandas as pd 

In [4]:
#from google.colab import drive
#drive.mount('/content/drive')

In [11]:
#loading datasets
data = pd.read_csv("wisc_bc_data.csv")

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
id                   569 non-null int64
diagnosis            569 non-null object
radius_mean          569 non-null float64
texture_mean         569 non-null float64
perimeter_mean       569 non-null float64
area_mean            569 non-null float64
smoothness_mean      569 non-null float64
compactness_mean     569 non-null float64
concavity_mean       569 non-null float64
points_mean          569 non-null float64
symmetry_mean        569 non-null float64
dimension_mean       569 non-null float64
radius_se            569 non-null float64
texture_se           569 non-null float64
perimeter_se         569 non-null float64
area_se              569 non-null float64
smoothness_se        569 non-null float64
compactness_se       569 non-null float64
concavity_se         569 non-null float64
points_se            569 non-null float64
symmetry_se          569 non-null float64
dimension_se    

In [13]:
#deleting useless columns
#deleting the "id" column
data.drop("id",axis=1,inplace=True)


In [0]:
#the result
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
diagnosis            569 non-null object
radius_mean          569 non-null float64
texture_mean         569 non-null float64
perimeter_mean       569 non-null float64
area_mean            569 non-null float64
smoothness_mean      569 non-null float64
compactness_mean     569 non-null float64
concavity_mean       569 non-null float64
points_mean          569 non-null float64
symmetry_mean        569 non-null float64
dimension_mean       569 non-null float64
radius_se            569 non-null float64
texture_se           569 non-null float64
perimeter_se         569 non-null float64
area_se              569 non-null float64
smoothness_se        569 non-null float64
compactness_se       569 non-null float64
concavity_se         569 non-null float64
points_se            569 non-null float64
symmetry_se          569 non-null float64
dimension_se         569 non-null float64
radius_worst  

In [16]:
data.head(5)
data.diagnosis.value_counts()


B    357
M    212
Name: diagnosis, dtype: int64

In [15]:
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         B        12.32         12.39           78.85      464.1   
1         B        10.60         18.95           69.28      346.4   
2         B        11.04         16.83           70.92      373.2   
3         B        11.28         13.39           73.00      384.8   
4         B        15.19         13.21           97.65      711.8   

   smoothness_mean  compactness_mean  concavity_mean  points_mean  \
0          0.10280           0.06981         0.03987      0.03700   
1          0.09688           0.11470         0.06387      0.02642   
2          0.10770           0.07804         0.03046      0.02480   
3          0.11640           0.11360         0.04635      0.04796   
4          0.07963           0.06934         0.03393      0.02657   

   symmetry_mean       ...         radius_worst  texture_worst  \
0         0.1959       ...                13.50          15.64   
1         0.1922       ...                11.88          22.94   
2         0.1714       ...                12.41          26.44   
3         0.1771       ...                11.92          15.77   
4         0.1721       ...                16.20          15.73   

   perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0            86.97       549.1            0.1385             0.1266   
1            78.28       424.8            0.1213             0.2515   
2            79.93       471.4            0.1369             0.1482   
3            76.53       434.0            0.1367             0.1822   
4           104.50       819.1            0.1126             0.1737   

   concavity_worst  points_worst  symmetry_worst  dimension_worst  
0          0.12420       0.09391          0.2827          0.06771  
1          0.19160       0.07926          0.2940          0.07587  
2          0.10670       0.07431          0.2998          0.07881  
3          0.08669       0.08611          0.2102          0.06784  
4          0.13620       0.08178          0.2487          0.06766  

[5 rows x 31 columns]

In [17]:
#finished the dataset preprocessing
#splitting dataset into training one and testing one
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size = 0.3,random_state=2)

In [0]:
#finding out the results
print(train.shape)
print(test.shape)

(398, 31)
(171, 31)


In [18]:
#making independent variables for training
train_X = train.iloc[:, 1:31]
#making responsible variables for training
train_y=train.diagnosis
#making independent variables for testing
test_X= test.iloc[:, 1:31]
#making responsible variables for testing
test_y =test.diagnosis#finding out the results


In [19]:
print(train_X.shape)
print(train_y.shape)
print(test_X.shape)
print(test_y.shape)

(398, 30)
(398,)
(171, 30)
(171,)


In [0]:
#Without Hyper Parameters Tuning
#Randomforest
#importing module
from sklearn.ensemble import RandomForestClassifier
#making the instance
model=RandomForestClassifier(random_state=123)
#learning
model.fit(train_X,train_y)
#Prediction
prediction=model.predict(test_X)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,test_y))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,test_y))

Accuracy: 0.935672514619883
Confusion Metrix:
 [[98  9]
 [ 2 62]]


/usr/local/anaconda/python3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [22]:
#Without Hyper Parameters Tuning
#SVM
#importing module
from sklearn import svm
#making the instance
model = svm.SVC(random_state=123)
#learning
model.fit(train_X,train_y)
#Prediction
prediction=model.predict(test_X)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,test_y))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,test_y))

Accuracy: 0.5847953216374269
Confusion Metrix:
 [[100  71]
 [  0   0]]


C:\Users\anusingh\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [21]:
#Without Hyper Parameters Tuning
#kNearestNeighbors
#importing module
from sklearn.neighbors import KNeighborsClassifier
#making the instance
model = KNeighborsClassifier()
#learning
model.fit(train_X,train_y)
#Prediction
prediction=model.predict(test_X)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,test_y))
#evaluation(Confusion Metrix)
print("Confusion Matrix:\n",metrics.confusion_matrix(prediction,test_y))

Accuracy: 0.9064327485380117
Confusion Matrix:
 [[96 12]
 [ 4 59]]


In [23]:
#With Hyper Parameters Tuning
#Randomforest
#importing modules
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
#making the instance
model=RandomForestClassifier()
#hyper parameters set
params = {'criterion':['gini','entropy'],
          'n_estimators':[10,15,20,25,30],
          'min_samples_leaf':[1,2,3],
          'min_samples_split':[3,4,5,6,7]}
#Making models with hyper parameters sets
model1 = GridSearchCV(model, param_grid=params, cv=5)
#learning
model1.fit(train_X,train_y)
#The best hyper parameters set
print("Best Hyper Parameters:\n",model1.best_params_)
#Prediction
prediction=model1.predict(test_X)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,test_y))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,test_y))




Best Hyper Parameters:
 {'criterion': 'gini', 'min_samples_leaf': 2, 'min_samples_split': 4, 'n_estimators': 20}
Accuracy: 0.9590643274853801
Confusion Metrix:
 [[98  5]
 [ 2 66]]


C:\Users\anusingh\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [24]:
#With Hyper Parameters Tuning
#SVM
#importing modules
from sklearn.model_selection import GridSearchCV
from sklearn import svm
#making the instance
model=svm.SVC()
#Hyper Parameters Set
params = {'C': [6,7,8,9,10,11,12], 
          'kernel': ['linear','rbf']}
#Making models with hyper parameters sets
model1 = GridSearchCV(model, param_grid=params, cv=10,n_jobs=-1)
#Learning
model1.fit(train_X,train_y)
#The best hyper parameters set
print("Best Hyper Parameters:\n",model1.best_params_)
#Prediction
prediction=model1.predict(test_X)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,test_y))
#evaluation(Confusion Metrix)
print("Confusion Matrix:\n",metrics.confusion_matrix(prediction,test_y))


Best Hyper Parameters:
 {'C': 11, 'kernel': 'linear'}
Accuracy: 0.9649122807017544
Confusion Matrix:
 [[98  4]
 [ 2 67]]


In [0]:
#With Hyper Parameters Tuning
#2-4,kNearestNeighbors
#importing modules
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
#making the instance
model = KNeighborsClassifier(n_jobs=-1)
#Hyper Parameters Set
params = {'n_neighbors':[5,7,9,11,13,15],'weights':['uniform', 'distance']}
#Making models with hyper parameters sets
model1 = GridSearchCV(model, param_grid=params, cv=10,n_jobs=-1)
#Learning
model1.fit(train_X,train_y)
#The best hyper parameters set
print("Best Hyper Parameters:\n",model1.best_params_)
#Prediction
prediction=model1.predict(test_X)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,test_y))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,test_y))

Best Hyper Parameters:
 {'n_neighbors': 5, 'weights': 'uniform'}
Accuracy: 0.9064327485380117
Confusion Metrix:
 [[96 12]
 [ 4 59]]


In [26]:
model1.cv_results_

C:\Users\anusingh\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\anusingh\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\anusingh\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\anusingh\Anaconda3\lib\site-packages\

{'mean_fit_time': array([10.17083745,  0.04266622, 10.09827728,  0.04058008, 12.47588062,
         0.04011889,  8.80333824,  0.03876634, 10.52066119,  0.03519909,
        10.32637403,  0.05046258,  9.56610024,  0.03806031]),
 'std_fit_time': array([5.16154480e+00, 4.82937374e-03, 5.28783327e+00, 3.09466012e-03,
        6.64998076e+00, 4.02499102e-03, 3.26858836e+00, 2.52728678e-03,
        4.78567339e+00, 7.44865883e-03, 3.71233815e+00, 1.15031052e-02,
        3.85626506e+00, 1.92531290e-03]),
 'mean_score_time': array([0.00273771, 0.00549142, 0.00096991, 0.00429454, 0.00430024,
        0.00478005, 0.00208371, 0.00474763, 0.00183222, 0.00612695,
        0.00134382, 0.00557575, 0.00049965, 0.00515387]),
 'std_score_time': array([0.00155597, 0.00181887, 0.00172311, 0.00141685, 0.00515729,
        0.00124093, 0.00163327, 0.00202608, 0.00198776, 0.00694226,
        0.00155198, 0.00318554, 0.00120418, 0.00196199]),
 'param_C': masked_array(data=[6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 1

In [25]:
sensitivity = 59/63
# sensitivity should be higher for a good model.

In [0]:
#Suggesting Default hyper parameter for KNN